name: Dropwatch compilation workflow
on:
  push:
    branches: ["master", "dev"]
    tags:
      - v**
    paths-ignore:
      - "**.md"
      - "**.sh"
  pull_request:
    branches: ["master", "dev"]
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.md"
      - "**.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref}}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-dev libreadline-dev libnl-3-dev libnl-genl-3-dev libpcap-dev libnfnetlink-dev
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j
